#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Where2Study.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="w2s")]
	public partial class w2sDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdrzava(drzava instance);
    partial void Updatedrzava(drzava instance);
    partial void Deletedrzava(drzava instance);
    partial void Insertfakultet(fakultet instance);
    partial void Updatefakultet(fakultet instance);
    partial void Deletefakultet(fakultet instance);
    partial void Insertgrad(grad instance);
    partial void Updategrad(grad instance);
    partial void Deletegrad(grad instance);
    partial void Insertjezik(jezik instance);
    partial void Updatejezik(jezik instance);
    partial void Deletejezik(jezik instance);
    partial void Insertkontinent(kontinent instance);
    partial void Updatekontinent(kontinent instance);
    partial void Deletekontinent(kontinent instance);
    partial void Insertpredmet(predmet instance);
    partial void Updatepredmet(predmet instance);
    partial void Deletepredmet(predmet instance);
    partial void Insertsmjer(smjer instance);
    partial void Updatesmjer(smjer instance);
    partial void Deletesmjer(smjer instance);
    partial void Insertstupanj(stupanj instance);
    partial void Updatestupanj(stupanj instance);
    partial void Deletestupanj(stupanj instance);
    #endregion
		
		public w2sDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["w2sDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public w2sDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public w2sDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public w2sDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public w2sDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<drzava> drzavas
		{
			get
			{
				return this.GetTable<drzava>();
			}
		}
		
		public System.Data.Linq.Table<stupanj_tekst> stupanj_teksts
		{
			get
			{
				return this.GetTable<stupanj_tekst>();
			}
		}
		
		public System.Data.Linq.Table<drzava_tekst> drzava_teksts
		{
			get
			{
				return this.GetTable<drzava_tekst>();
			}
		}
		
		public System.Data.Linq.Table<fakultet> fakultets
		{
			get
			{
				return this.GetTable<fakultet>();
			}
		}
		
		public System.Data.Linq.Table<fakultet_tekst> fakultet_teksts
		{
			get
			{
				return this.GetTable<fakultet_tekst>();
			}
		}
		
		public System.Data.Linq.Table<grad> grads
		{
			get
			{
				return this.GetTable<grad>();
			}
		}
		
		public System.Data.Linq.Table<grad_tekst> grad_teksts
		{
			get
			{
				return this.GetTable<grad_tekst>();
			}
		}
		
		public System.Data.Linq.Table<jezik> jeziks
		{
			get
			{
				return this.GetTable<jezik>();
			}
		}
		
		public System.Data.Linq.Table<jezik_tekst> jezik_teksts
		{
			get
			{
				return this.GetTable<jezik_tekst>();
			}
		}
		
		public System.Data.Linq.Table<kontinent> kontinents
		{
			get
			{
				return this.GetTable<kontinent>();
			}
		}
		
		public System.Data.Linq.Table<kontinent_tekst> kontinent_teksts
		{
			get
			{
				return this.GetTable<kontinent_tekst>();
			}
		}
		
		public System.Data.Linq.Table<predmet> predmets
		{
			get
			{
				return this.GetTable<predmet>();
			}
		}
		
		public System.Data.Linq.Table<predmet_tekst> predmet_teksts
		{
			get
			{
				return this.GetTable<predmet_tekst>();
			}
		}
		
		public System.Data.Linq.Table<smjer> smjers
		{
			get
			{
				return this.GetTable<smjer>();
			}
		}
		
		public System.Data.Linq.Table<smjer_predmet> smjer_predmets
		{
			get
			{
				return this.GetTable<smjer_predmet>();
			}
		}
		
		public System.Data.Linq.Table<smjer_tekst> smjer_teksts
		{
			get
			{
				return this.GetTable<smjer_tekst>();
			}
		}
		
		public System.Data.Linq.Table<stupanj> stupanjs
		{
			get
			{
				return this.GetTable<stupanj>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.drzava")]
	public partial class drzava : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _id_kontinent;
		
		private EntitySet<grad> _grads;
		
		private EntityRef<kontinent> _kontinent;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_kontinentChanging(System.Nullable<int> value);
    partial void Onid_kontinentChanged();
    #endregion
		
		public drzava()
		{
			this._grads = new EntitySet<grad>(new Action<grad>(this.attach_grads), new Action<grad>(this.detach_grads));
			this._kontinent = default(EntityRef<kontinent>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_kontinent", DbType="Int")]
		public System.Nullable<int> id_kontinent
		{
			get
			{
				return this._id_kontinent;
			}
			set
			{
				if ((this._id_kontinent != value))
				{
					if (this._kontinent.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_kontinentChanging(value);
					this.SendPropertyChanging();
					this._id_kontinent = value;
					this.SendPropertyChanged("id_kontinent");
					this.Onid_kontinentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="drzava_grad", Storage="_grads", ThisKey="id", OtherKey="id_drzava")]
		public EntitySet<grad> grads
		{
			get
			{
				return this._grads;
			}
			set
			{
				this._grads.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kontinent_drzava", Storage="_kontinent", ThisKey="id_kontinent", OtherKey="id", IsForeignKey=true, DeleteRule="SET NULL")]
		public kontinent kontinent
		{
			get
			{
				return this._kontinent.Entity;
			}
			set
			{
				kontinent previousValue = this._kontinent.Entity;
				if (((previousValue != value) 
							|| (this._kontinent.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kontinent.Entity = null;
						previousValue.drzavas.Remove(this);
					}
					this._kontinent.Entity = value;
					if ((value != null))
					{
						value.drzavas.Add(this);
						this._id_kontinent = value.id;
					}
					else
					{
						this._id_kontinent = default(Nullable<int>);
					}
					this.SendPropertyChanged("kontinent");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_grads(grad entity)
		{
			this.SendPropertyChanging();
			entity.drzava = this;
		}
		
		private void detach_grads(grad entity)
		{
			this.SendPropertyChanging();
			entity.drzava = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.stupanj_tekst")]
	public partial class stupanj_tekst
	{
		
		private System.Nullable<int> _id_stupanj;
		
		private System.Nullable<int> _id_jezik;
		
		private string _naziv;
		
		public stupanj_tekst()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_stupanj", DbType="Int")]
		public System.Nullable<int> id_stupanj
		{
			get
			{
				return this._id_stupanj;
			}
			set
			{
				if ((this._id_stupanj != value))
				{
					this._id_stupanj = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jezik", DbType="Int")]
		public System.Nullable<int> id_jezik
		{
			get
			{
				return this._id_jezik;
			}
			set
			{
				if ((this._id_jezik != value))
				{
					this._id_jezik = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_naziv", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string naziv
		{
			get
			{
				return this._naziv;
			}
			set
			{
				if ((this._naziv != value))
				{
					this._naziv = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.drzava_tekst")]
	public partial class drzava_tekst
	{
		
		private System.Nullable<int> _id_drzava;
		
		private System.Nullable<int> _id_jezik;
		
		private string _tekst;
		
		public drzava_tekst()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_drzava", DbType="Int")]
		public System.Nullable<int> id_drzava
		{
			get
			{
				return this._id_drzava;
			}
			set
			{
				if ((this._id_drzava != value))
				{
					this._id_drzava = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jezik", DbType="Int")]
		public System.Nullable<int> id_jezik
		{
			get
			{
				return this._id_jezik;
			}
			set
			{
				if ((this._id_jezik != value))
				{
					this._id_jezik = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tekst", DbType="VarChar(MAX)")]
		public string tekst
		{
			get
			{
				return this._tekst;
			}
			set
			{
				if ((this._tekst != value))
				{
					this._tekst = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.fakultet")]
	public partial class fakultet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _id_grad;
		
		private string _adresa_fakulteta;
		
		private string _broj_telefona;
		
		private System.Nullable<int> _id_sveuciliste;
		
		private string _web;
		
		private EntitySet<smjer> _smjers;
		
		private EntityRef<grad> _grad;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_gradChanging(System.Nullable<int> value);
    partial void Onid_gradChanged();
    partial void Onadresa_fakultetaChanging(string value);
    partial void Onadresa_fakultetaChanged();
    partial void Onbroj_telefonaChanging(string value);
    partial void Onbroj_telefonaChanged();
    partial void Onid_sveucilisteChanging(System.Nullable<int> value);
    partial void Onid_sveucilisteChanged();
    partial void OnwebChanging(string value);
    partial void OnwebChanged();
    #endregion
		
		public fakultet()
		{
			this._smjers = new EntitySet<smjer>(new Action<smjer>(this.attach_smjers), new Action<smjer>(this.detach_smjers));
			this._grad = default(EntityRef<grad>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_grad", DbType="Int")]
		public System.Nullable<int> id_grad
		{
			get
			{
				return this._id_grad;
			}
			set
			{
				if ((this._id_grad != value))
				{
					if (this._grad.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_gradChanging(value);
					this.SendPropertyChanging();
					this._id_grad = value;
					this.SendPropertyChanged("id_grad");
					this.Onid_gradChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresa_fakulteta", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string adresa_fakulteta
		{
			get
			{
				return this._adresa_fakulteta;
			}
			set
			{
				if ((this._adresa_fakulteta != value))
				{
					this.Onadresa_fakultetaChanging(value);
					this.SendPropertyChanging();
					this._adresa_fakulteta = value;
					this.SendPropertyChanged("adresa_fakulteta");
					this.Onadresa_fakultetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_broj_telefona", DbType="VarChar(32)")]
		public string broj_telefona
		{
			get
			{
				return this._broj_telefona;
			}
			set
			{
				if ((this._broj_telefona != value))
				{
					this.Onbroj_telefonaChanging(value);
					this.SendPropertyChanging();
					this._broj_telefona = value;
					this.SendPropertyChanged("broj_telefona");
					this.Onbroj_telefonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sveuciliste", DbType="Int")]
		public System.Nullable<int> id_sveuciliste
		{
			get
			{
				return this._id_sveuciliste;
			}
			set
			{
				if ((this._id_sveuciliste != value))
				{
					this.Onid_sveucilisteChanging(value);
					this.SendPropertyChanging();
					this._id_sveuciliste = value;
					this.SendPropertyChanged("id_sveuciliste");
					this.Onid_sveucilisteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_web", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string web
		{
			get
			{
				return this._web;
			}
			set
			{
				if ((this._web != value))
				{
					this.OnwebChanging(value);
					this.SendPropertyChanging();
					this._web = value;
					this.SendPropertyChanged("web");
					this.OnwebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="fakultet_smjer", Storage="_smjers", ThisKey="id", OtherKey="id_fakultet")]
		public EntitySet<smjer> smjers
		{
			get
			{
				return this._smjers;
			}
			set
			{
				this._smjers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="grad_fakultet", Storage="_grad", ThisKey="id_grad", OtherKey="id", IsForeignKey=true, DeleteRule="SET NULL")]
		public grad grad
		{
			get
			{
				return this._grad.Entity;
			}
			set
			{
				grad previousValue = this._grad.Entity;
				if (((previousValue != value) 
							|| (this._grad.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._grad.Entity = null;
						previousValue.fakultets.Remove(this);
					}
					this._grad.Entity = value;
					if ((value != null))
					{
						value.fakultets.Add(this);
						this._id_grad = value.id;
					}
					else
					{
						this._id_grad = default(Nullable<int>);
					}
					this.SendPropertyChanged("grad");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_smjers(smjer entity)
		{
			this.SendPropertyChanging();
			entity.fakultet = this;
		}
		
		private void detach_smjers(smjer entity)
		{
			this.SendPropertyChanging();
			entity.fakultet = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.fakultet_tekst")]
	public partial class fakultet_tekst
	{
		
		private System.Nullable<int> _id_fakultet;
		
		private System.Nullable<int> _id_jezik;
		
		private string _naziv;

        private string _opis;

		public fakultet_tekst()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_fakultet", DbType="Int")]
		public System.Nullable<int> id_fakultet
		{
			get
			{
				return this._id_fakultet;
			}
			set
			{
				if ((this._id_fakultet != value))
				{
					this._id_fakultet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jezik", DbType="Int")]
		public System.Nullable<int> id_jezik
		{
			get
			{
				return this._id_jezik;
			}
			set
			{
				if ((this._id_jezik != value))
				{
					this._id_jezik = value;
				}
			}
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_naziv", DbType = "text")]
        public string naziv
        {
            get
            {
                return this._naziv;
            }
            set
            {
                if ((this._naziv != value))
                {
                    this._naziv = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opis", DbType="text")]
		public string opis
		{
			get
			{
				return this._opis;
			}
			set
			{
				if ((this._opis != value))
				{
					this._opis = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.grad")]
	public partial class grad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _id_drzava;
		
		private EntitySet<fakultet> _fakultets;
		
		private EntityRef<drzava> _drzava;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_drzavaChanging(System.Nullable<int> value);
    partial void Onid_drzavaChanged();
    #endregion
		
		public grad()
		{
			this._fakultets = new EntitySet<fakultet>(new Action<fakultet>(this.attach_fakultets), new Action<fakultet>(this.detach_fakultets));
			this._drzava = default(EntityRef<drzava>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_drzava", DbType="Int")]
		public System.Nullable<int> id_drzava
		{
			get
			{
				return this._id_drzava;
			}
			set
			{
				if ((this._id_drzava != value))
				{
					if (this._drzava.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_drzavaChanging(value);
					this.SendPropertyChanging();
					this._id_drzava = value;
					this.SendPropertyChanged("id_drzava");
					this.Onid_drzavaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="grad_fakultet", Storage="_fakultets", ThisKey="id", OtherKey="id_grad")]
		public EntitySet<fakultet> fakultets
		{
			get
			{
				return this._fakultets;
			}
			set
			{
				this._fakultets.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="drzava_grad", Storage="_drzava", ThisKey="id_drzava", OtherKey="id", IsForeignKey=true, DeleteRule="SET NULL")]
		public drzava drzava
		{
			get
			{
				return this._drzava.Entity;
			}
			set
			{
				drzava previousValue = this._drzava.Entity;
				if (((previousValue != value) 
							|| (this._drzava.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._drzava.Entity = null;
						previousValue.grads.Remove(this);
					}
					this._drzava.Entity = value;
					if ((value != null))
					{
						value.grads.Add(this);
						this._id_drzava = value.id;
					}
					else
					{
						this._id_drzava = default(Nullable<int>);
					}
					this.SendPropertyChanged("drzava");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_fakultets(fakultet entity)
		{
			this.SendPropertyChanging();
			entity.grad = this;
		}
		
		private void detach_fakultets(fakultet entity)
		{
			this.SendPropertyChanging();
			entity.grad = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.grad_tekst")]
	public partial class grad_tekst
	{
		
		private System.Nullable<int> _id_grad;
		
		private System.Nullable<int> _id_jezik;
		
		private string _tekst;
		
		public grad_tekst()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_grad", DbType="Int")]
		public System.Nullable<int> id_grad
		{
			get
			{
				return this._id_grad;
			}
			set
			{
				if ((this._id_grad != value))
				{
					this._id_grad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jezik", DbType="Int")]
		public System.Nullable<int> id_jezik
		{
			get
			{
				return this._id_jezik;
			}
			set
			{
				if ((this._id_jezik != value))
				{
					this._id_jezik = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tekst", DbType="VarChar(MAX)")]
		public string tekst
		{
			get
			{
				return this._tekst;
			}
			set
			{
				if ((this._tekst != value))
				{
					this._tekst = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jezik")]
	public partial class jezik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _kratica;
		
		private string _ime_jezika;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnkraticaChanging(string value);
    partial void OnkraticaChanged();
    partial void Onime_jezikaChanging(string value);
    partial void Onime_jezikaChanged();
    #endregion
		
		public jezik()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kratica", DbType="VarChar(5)")]
		public string kratica
		{
			get
			{
				return this._kratica;
			}
			set
			{
				if ((this._kratica != value))
				{
					this.OnkraticaChanging(value);
					this.SendPropertyChanging();
					this._kratica = value;
					this.SendPropertyChanged("kratica");
					this.OnkraticaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ime_jezika", DbType="VarChar(30)")]
		public string ime_jezika
		{
			get
			{
				return this._ime_jezika;
			}
			set
			{
				if ((this._ime_jezika != value))
				{
					this.Onime_jezikaChanging(value);
					this.SendPropertyChanging();
					this._ime_jezika = value;
					this.SendPropertyChanged("ime_jezika");
					this.Onime_jezikaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jezik_tekst")]
	public partial class jezik_tekst
	{
		
		private System.Nullable<int> _id_jezik;
		
		private string _tekst;
		
		private System.Nullable<int> _id_id;
		
		public jezik_tekst()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jezik", DbType="Int")]
		public System.Nullable<int> id_jezik
		{
			get
			{
				return this._id_jezik;
			}
			set
			{
				if ((this._id_jezik != value))
				{
					this._id_jezik = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tekst", DbType="VarChar(20)")]
		public string tekst
		{
			get
			{
				return this._tekst;
			}
			set
			{
				if ((this._tekst != value))
				{
					this._tekst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_id", DbType="Int")]
		public System.Nullable<int> id_id
		{
			get
			{
				return this._id_id;
			}
			set
			{
				if ((this._id_id != value))
				{
					this._id_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kontinent")]
	public partial class kontinent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private EntitySet<drzava> _drzavas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
		
		public kontinent()
		{
			this._drzavas = new EntitySet<drzava>(new Action<drzava>(this.attach_drzavas), new Action<drzava>(this.detach_drzavas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kontinent_drzava", Storage="_drzavas", ThisKey="id", OtherKey="id_kontinent")]
		public EntitySet<drzava> drzavas
		{
			get
			{
				return this._drzavas;
			}
			set
			{
				this._drzavas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_drzavas(drzava entity)
		{
			this.SendPropertyChanging();
			entity.kontinent = this;
		}
		
		private void detach_drzavas(drzava entity)
		{
			this.SendPropertyChanging();
			entity.kontinent = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kontinent_tekst")]
	public partial class kontinent_tekst
	{
		
		private System.Nullable<int> _id_kontinent;
		
		private System.Nullable<int> _id_jezik;
		
		private string _tekst;
		
		public kontinent_tekst()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_kontinent", DbType="Int")]
		public System.Nullable<int> id_kontinent
		{
			get
			{
				return this._id_kontinent;
			}
			set
			{
				if ((this._id_kontinent != value))
				{
					this._id_kontinent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jezik", DbType="Int")]
		public System.Nullable<int> id_jezik
		{
			get
			{
				return this._id_jezik;
			}
			set
			{
				if ((this._id_jezik != value))
				{
					this._id_jezik = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tekst", DbType="VarChar(MAX)")]
		public string tekst
		{
			get
			{
				return this._tekst;
			}
			set
			{
				if ((this._tekst != value))
				{
					this._tekst = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.predmet")]
	public partial class predmet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<short> _ects;
		
		private System.Nullable<short> _god_studija;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnectsChanging(System.Nullable<short> value);
    partial void OnectsChanged();
    partial void Ongod_studijaChanging(System.Nullable<short> value);
    partial void Ongod_studijaChanged();
    #endregion
		
		public predmet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ects", DbType="SmallInt")]
		public System.Nullable<short> ects
		{
			get
			{
				return this._ects;
			}
			set
			{
				if ((this._ects != value))
				{
					this.OnectsChanging(value);
					this.SendPropertyChanging();
					this._ects = value;
					this.SendPropertyChanged("ects");
					this.OnectsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_god_studija", DbType="SmallInt")]
		public System.Nullable<short> god_studija
		{
			get
			{
				return this._god_studija;
			}
			set
			{
				if ((this._god_studija != value))
				{
					this.Ongod_studijaChanging(value);
					this.SendPropertyChanging();
					this._god_studija = value;
					this.SendPropertyChanged("god_studija");
					this.Ongod_studijaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.predmet_tekst")]
	public partial class predmet_tekst
	{
		
		private System.Nullable<int> _id_predmet;
		
		private System.Nullable<int> _id_jezik;
		
		private string _tekst;
		
		public predmet_tekst()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_predmet", DbType="Int")]
		public System.Nullable<int> id_predmet
		{
			get
			{
				return this._id_predmet;
			}
			set
			{
				if ((this._id_predmet != value))
				{
					this._id_predmet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jezik", DbType="Int")]
		public System.Nullable<int> id_jezik
		{
			get
			{
				return this._id_jezik;
			}
			set
			{
				if ((this._id_jezik != value))
				{
					this._id_jezik = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tekst", DbType="VarChar(MAX)")]
		public string tekst
		{
			get
			{
				return this._tekst;
			}
			set
			{
				if ((this._tekst != value))
				{
					this._tekst = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.smjer")]
	public partial class smjer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _id_fakultet;
		
		private System.Nullable<int> _id_stupanj;
		
		private EntityRef<fakultet> _fakultet;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_fakultetChanging(System.Nullable<int> value);
    partial void Onid_fakultetChanged();
    partial void Onid_stupanjChanging(System.Nullable<int> value);
    partial void Onid_stupanjChanged();
    #endregion
		
		public smjer()
		{
			this._fakultet = default(EntityRef<fakultet>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_fakultet", DbType="Int")]
		public System.Nullable<int> id_fakultet
		{
			get
			{
				return this._id_fakultet;
			}
			set
			{
				if ((this._id_fakultet != value))
				{
					if (this._fakultet.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_fakultetChanging(value);
					this.SendPropertyChanging();
					this._id_fakultet = value;
					this.SendPropertyChanged("id_fakultet");
					this.Onid_fakultetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_stupanj", DbType="Int")]
		public System.Nullable<int> id_stupanj
		{
			get
			{
				return this._id_stupanj;
			}
			set
			{
				if ((this._id_stupanj != value))
				{
					this.Onid_stupanjChanging(value);
					this.SendPropertyChanging();
					this._id_stupanj = value;
					this.SendPropertyChanged("id_stupanj");
					this.Onid_stupanjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="fakultet_smjer", Storage="_fakultet", ThisKey="id_fakultet", OtherKey="id", IsForeignKey=true, DeleteRule="SET NULL")]
		public fakultet fakultet
		{
			get
			{
				return this._fakultet.Entity;
			}
			set
			{
				fakultet previousValue = this._fakultet.Entity;
				if (((previousValue != value) 
							|| (this._fakultet.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._fakultet.Entity = null;
						previousValue.smjers.Remove(this);
					}
					this._fakultet.Entity = value;
					if ((value != null))
					{
						value.smjers.Add(this);
						this._id_fakultet = value.id;
					}
					else
					{
						this._id_fakultet = default(Nullable<int>);
					}
					this.SendPropertyChanged("fakultet");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.smjer_predmet")]
	public partial class smjer_predmet
	{
		
		private System.Nullable<int> _id_smjer;
		
		private System.Nullable<int> _id_predmet;
		
		public smjer_predmet()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_smjer", DbType="Int")]
		public System.Nullable<int> id_smjer
		{
			get
			{
				return this._id_smjer;
			}
			set
			{
				if ((this._id_smjer != value))
				{
					this._id_smjer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_predmet", DbType="Int")]
		public System.Nullable<int> id_predmet
		{
			get
			{
				return this._id_predmet;
			}
			set
			{
				if ((this._id_predmet != value))
				{
					this._id_predmet = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.smjer_tekst")]
	public partial class smjer_tekst
	{
		
		private System.Nullable<int> _id_smjer;
		
		private System.Nullable<int> _id_jezik;
		
		private string _tekst;
		
		public smjer_tekst()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_smjer", DbType="Int")]
		public System.Nullable<int> id_smjer
		{
			get
			{
				return this._id_smjer;
			}
			set
			{
				if ((this._id_smjer != value))
				{
					this._id_smjer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jezik", DbType="Int")]
		public System.Nullable<int> id_jezik
		{
			get
			{
				return this._id_jezik;
			}
			set
			{
				if ((this._id_jezik != value))
				{
					this._id_jezik = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tekst", DbType="VarChar(MAX)")]
		public string tekst
		{
			get
			{
				return this._tekst;
			}
			set
			{
				if ((this._tekst != value))
				{
					this._tekst = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.stupanj")]
	public partial class stupanj : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<byte> _trajanje;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntrajanjeChanging(System.Nullable<byte> value);
    partial void OntrajanjeChanged();
    #endregion
		
		public stupanj()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trajanje", DbType="TinyInt")]
		public System.Nullable<byte> trajanje
		{
			get
			{
				return this._trajanje;
			}
			set
			{
				if ((this._trajanje != value))
				{
					this.OntrajanjeChanging(value);
					this.SendPropertyChanging();
					this._trajanje = value;
					this.SendPropertyChanged("trajanje");
					this.OntrajanjeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
